"""Academic Sentinel Data Models.

Defines channels, priority tiers, tasks, submissions, and alerts for the
Jarvis X autonomous homework and academic tracking system.
"""

from __future__ import annotations
from dataclasses import dataclass, field
from enum import Enum
import time
from typing import Any, Dict, List, Optional


class ChannelSource(str, Enum):
    EMAIL = "EMAIL"
    GCR = "GCR"  # Google Classroom
    TEAMS = "TEAMS"  # Microsoft Teams
    WHATSAPP = "WHATSAPP"  # WhatsApp Class Groups
    ECURRICULA = "ECURRICULA"  # SRM eCurricula Portal
    NPTEL = "NPTEL"  # SWAYAM / NPTEL Weekly Coursework
    SRM_STEP_JAVA = "SRM_STEP_JAVA"  # SRM Student Talent Enhancement Program (Java Track)


class TaskPriority(str, Enum):
    EMERGENCY = "EMERGENCY"  # Due within 12 hours
    URGENT = "URGENT"        # Due within 24 hours
    NORMAL = "NORMAL"        # Due within 3 days
    LOW = "LOW"              # Due in > 3 days


class TaskType(str, Enum):
    WORKSHEET = "WORKSHEET"
    MCQ_ASSESSMENT = "MCQ_ASSESSMENT"
    NPTEL_ASSIGNMENT = "NPTEL_ASSIGNMENT"
    JAVA_CODING_CHALLENGE = "JAVA_CODING_CHALLENGE"
    CODING_PROJECT = "CODING_PROJECT"
    PROJECT = "PROJECT"
    GENERAL = "GENERAL"


class TaskStatus(str, Enum):
    DISCOVERED = "DISCOVERED"
    PARSED = "PARSED"
    SOLVED = "SOLVED"
    COMPILED = "COMPILED"
    ALERTED = "ALERTED"
    SUBMITTED = "SUBMITTED"
    FAILED = "FAILED"


@dataclass
class AcademicTask:
    """Represents a unified academic homework, assignment, or assessment item."""
    task_id: str
    channel: ChannelSource
    course_code: str
    course_name: str
    title: str
    description: str
    deadline_epoch: float
    priority: TaskPriority = TaskPriority.NORMAL
    task_type: TaskType = TaskType.GENERAL
    faculty_name: Optional[str] = None
    questions: List[Dict[str, Any]] = field(default_factory=list)
    solution_text: Optional[str] = None
    generated_code: Optional[Dict[str, str]] = field(default_factory=dict) # filename -> code
    compiled_docx: Optional[str] = None
    compiled_pdf: Optional[str] = None
    submission_link: Optional[str] = None
    score_achieved: Optional[float] = None
    status: TaskStatus = TaskStatus.DISCOVERED
    created_at: float = field(default_factory=time.time)
    updated_at: float = field(default_factory=time.time)

    @property
    def hours_remaining(self) -> float:
        return max(0.0, (self.deadline_epoch - time.time()) / 3600.0)

    def to_dict(self) -> Dict[str, Any]:
        return {
            "task_id": self.task_id,
            "channel": self.channel.value,
            "course_code": self.course_code,
            "course_name": self.course_name,
            "title": self.title,
            "description": self.description,
            "deadline_epoch": self.deadline_epoch,
            "priority": self.priority.value,
            "task_type": self.task_type.value,
            "faculty_name": self.faculty_name,
            "questions": self.questions,
            "solution_text": self.solution_text,
            "generated_code": self.generated_code,
            "compiled_docx": self.compiled_docx,
            "compiled_pdf": self.compiled_pdf,
            "submission_link": self.submission_link,
            "score_achieved": self.score_achieved,
            "status": self.status.value,
            "created_at": self.created_at,
            "updated_at": self.updated_at,
        }

    @classmethod
    def from_dict(cls, data: Dict[str, Any]) -> AcademicTask:
        try:
            p = TaskPriority(data.get("priority", "NORMAL"))
        except ValueError:
            p = TaskPriority.NORMAL

        try:
            t = TaskType(data.get("task_type", "GENERAL"))
        except ValueError:
            t = TaskType.GENERAL

        return cls(
            task_id=data["task_id"],
            channel=ChannelSource(data["channel"]),
            course_code=data["course_code"],
            course_name=data["course_name"],
            title=data["title"],
            description=data["description"],
            deadline_epoch=data["deadline_epoch"],
            priority=p,
            task_type=t,
            faculty_name=data.get("faculty_name"),
            questions=data.get("questions", []),
            solution_text=data.get("solution_text"),
            generated_code=data.get("generated_code", {}),
            compiled_docx=data.get("compiled_docx"),
            compiled_pdf=data.get("compiled_pdf"),
            submission_link=data.get("submission_link"),
            score_achieved=data.get("score_achieved"),
            status=TaskStatus(data.get("status", "DISCOVERED")),
            created_at=data.get("created_at", time.time()),
            updated_at=data.get("updated_at", time.time()),
        )


@dataclass
class AlertEvent:
    """Represents a proactive notification generated by the Sentinel."""
    event_id: str
    task_id: str
    channel: ChannelSource
    urgency: TaskPriority
    title: str
    message: str
    spoken_text: str
    delivered: bool = False
    timestamp: float = field(default_factory=time.time)


@dataclass
class StudentProfile:
    """Static student profile credentials for institutional documents and portal calls."""
    student_name: str = "RAM CHARAN VANGA"
    full_name: str = "VANGA RAM CHARAN VANGA RAM CHARAN"
    register_number: str = "RA2511027010164"
    department: str = "COMPUTER SCIENCE AND ENGINEERING WITH SPECIALIZATION IN BIG DATA ANALYTICS"
    semester: int = 3
    email: str = "vangaramcharan2007@gmail.com"
