"""Model-Agnostic Semantic Visual Evaluator for Jarvis X: GENESIS.

Performs semantic scene evaluation comparing visual goals against perceived canvas state:
- Computes goal match scores, completeness, and confidence
- Identifies missing elements, scale errors, and spatial position deviations
"""

from __future__ import annotations
from typing import Dict, Any, List, Optional
from dataclasses import dataclass, field

from jarvisx.computer_use.semantic_canvas_perception import SceneState, DetectedVisualObject


@dataclass
class VisualEvaluation:
    """Evaluation report generated by analyzing current canvas scene against goal."""
    goal: str
    goal_match_score: float  # 0.0 to 1.0
    completion_status: str  # "INCOMPLETE", "SATISFACTORY", "COMPLETE"
    missing_elements: List[str] = field(default_factory=list)
    scale_errors: List[str] = field(default_factory=list)
    position_errors: List[str] = field(default_factory=list)
    composition_errors: List[str] = field(default_factory=list)
    detected_elements: List[str] = field(default_factory=list)
    confidence: float = 0.90
    recommendations: List[str] = field(default_factory=list)

    @property
    def is_satisfactory(self) -> bool:
        return self.goal_match_score >= 0.70 and not self.missing_elements


class VisualEvaluator:
    """Evaluates canvas completeness and visual correctness against natural-language goals."""

    def evaluate_scene(self, goal: str, scene: SceneState) -> VisualEvaluation:
        """Evaluate a SceneState against an open-ended natural language visual goal."""
        detected_names = [obj.name.lower() for obj in scene.detected_objects]
        missing = list(scene.missing_expected_elements)
        scale_errors = []
        position_errors = []
        composition_errors = []
        recommendations = []

        # 1. Analyze scale errors
        for obj in scene.detected_objects:
            if obj.name.lower() in ("mountain", "mountains", "castle", "ocean", "landscape") and obj.relative_scale < 0.15:
                scale_errors.append(f"{obj.name} is too small (scale {obj.relative_scale:.2f} < 0.15)")
                recommendations.append(f"Enlarge {obj.name} to cover a broader area")
            elif obj.name.lower() in ("sun", "moon", "star") and obj.relative_scale > 0.35:
                scale_errors.append(f"{obj.name} is too large (scale {obj.relative_scale:.2f} > 0.35)")
                recommendations.append(f"Reduce {obj.name} radius to prevent visual clipping")

        # 2. Analyze spatial positioning errors
        for obj in scene.detected_objects:
            # Sun or moon should ideally be in upper regions
            if obj.name.lower() in ("sun", "moon", "clouds", "cloud") and obj.center[1] > (scene.canvas_bounds[1] + scene.canvas_dimensions[1] * 0.45):
                position_errors.append(f"{obj.name} is positioned too low on canvas")
                recommendations.append(f"Elevate {obj.name} toward upper sky region")
            # Base subjects (bridge, lake, ground, ocean) should be in lower regions
            elif obj.name.lower() in ("ground", "lake", "ocean", "floor", "bridge", "road") and obj.center[1] < (scene.canvas_bounds[1] + scene.canvas_dimensions[1] * 0.45):
                position_errors.append(f"{obj.name} is positioned too high")
                recommendations.append(f"Shift {obj.name} toward lower canvas ground region")

        # 3. Analyze composition balance
        density = scene.spatial_density
        left_dense = density.get("top_left", 0) + density.get("bottom_left", 0)
        right_dense = density.get("top_right", 0) + density.get("bottom_right", 0)
        if abs(left_dense - right_dense) > 0.60:
            dominant_side = "left" if left_dense > right_dense else "right"
            composition_errors.append(f"Composition is heavily imbalanced toward {dominant_side}")

        # 4. Compute Goal Match Score
        if scene.total_strokes_detected == 0:
            match_score = 0.0
        else:
            total_expected = max(1, len(detected_names) + len(missing))
            present_ratio = len(detected_names) / total_expected
            penalty = (0.05 * len(scale_errors)) + (0.05 * len(position_errors)) + (0.05 * len(composition_errors))
            match_score = max(0.15, min(1.0, round(present_ratio - penalty, 2)))

        if match_score >= 0.80 and not missing and not scale_errors:
            status = "COMPLETE"
        elif match_score >= 0.60:
            status = "SATISFACTORY"
        else:
            status = "INCOMPLETE"

        for m in missing:
            recommendations.append(f"Draw missing element '{m}' onto active canvas")

        return VisualEvaluation(
            goal=goal,
            goal_match_score=match_score,
            completion_status=status,
            missing_elements=missing,
            scale_errors=scale_errors,
            position_errors=position_errors,
            composition_errors=composition_errors,
            detected_elements=detected_names,
            confidence=scene.confidence,
            recommendations=recommendations
        )
