"""DevOps and CI/CD Automation Agent (Layer 3 - Agent Layer).

Executes automated repository administration, Pull Request staging, and issue resolution workflows.
"""

from typing import Any, Dict, Optional
from jarvisx.agents.base import OperationalAgent
from jarvisx.automation.vcs_ci import VCSEngine


class DevOpsAgent(OperationalAgent):
    """Specialized worker for automated repository DevOps and CI/CD operations."""

    __test__ = False

    def __init__(self, name: str = "devops_agent", vcs_engine: Optional[VCSEngine] = None):
        super().__init__(
            name=name,
            purpose="Automated Version Control System (VCS) and CI/CD Pull Request and release orchestration",
            capabilities=["pr_packaging", "issue_triaging", "release_bundling", "ci_validation"],
            permissions=["read_filesystem", "git_write", "api_dispatch"],
            hspw_multiplier=1.5,
        )
        self.vcs = vcs_engine or VCSEngine()

    def _execute_task(self, task: Dict[str, Any], **kwargs: Any) -> Dict[str, Any]:
        action = task.get("action", "status")

        if action in ("pr_create", "pull_request", "pr"):
            res = self.vcs.create_pull_request(
                title=task.get("title", "Automated Update"),
                description=task.get("description", "Generated by Alfred DevOpsAgent"),
                source_branch=task.get("branch", "feature-branch"),
                target_branch=task.get("base", "main"),
            )
            return {"status": "completed", "result": res}

        elif action in ("triage", "issue"):
            res = self.vcs.triage_issue(
                title=task.get("title", "Unknown issue"),
                body=task.get("body", "No details provided."),
            )
            return {"status": "completed", "result": res}

        elif action in ("release", "deploy"):
            res = self.vcs.package_release(
                version_tag=task.get("version", "v1.0.0"),
                release_notes=task.get("notes", "Standard release."),
            )
            return {"status": "completed", "result": res}

        elif action == "status":
            saved = self.metrics()["hours_saved"]
            output = (
                f"DEVOPS WORKSPACE STATUS:\n"
                f"  • Active Pull Requests: {len(self.vcs.pr_history)}\n"
                f"  • Triaged Issues: {len(self.vcs.issue_registry)}\n"
                f"  • Staged Releases: {len(self.vcs.releases)}\n"
                f"  • DevOps Time Saved: +{saved:.2f} HSPW"
            )
            return {"status": "completed", "output": output, "hspw": saved}

        return {"status": "error", "message": f"Unknown DevOps action: {action}"}
